### ISSUE TITLE
FNF exception for some TimeMaps

### ISSUE THREAD

**Issue by wjorda** [Thing342/MobileMemento#3]
Some TimeMaps known to contains mementos show up as empty in the app, throwing a FNF exception.

**Comment by wjorda** [comment]
Examples of URLs that throw this exception include include espn.go.com, and www.thing342.us

**Comment by wjorda** [comment]
Merged this with #6 to include info about potential crashes.

**Comment by wjorda** [comment]
Issue was caused by stupid people at LANL. Fixed with switch to ODU aggregator.

**Comment by machawk1** [comment]
@Thing342 The ODU aggregator behaves a little differently and I am unsure if it contains the same set of archives as the LANL one. Further, I do not think that it implements TimeMap pagination. @jbrunelle might know more about the implications of switching.

**Comment by jbrunelle** [comment]
The lanl aggr is not working properly. Sawood told us to use this one. Close enough for government work.

-- Justin F. Brunelle

-------- Original message --------

**Comment by jbrunelle** [comment]
Wes:

Is this the most recent version:

http://www.thing342.us/mobile-mink/mobileMink-latest.apk (last updated 18 April 8:58 EST)

I'm still seeing crashes on mobile URIs.

Thanks!

Justin F. Brunelle
Old Dominion University Department of Computer Science

## Web Science and Digital Libraries Research Group - PhD Student

Engineering & Computational Sciences Bldg
4700 Elkhorn Ave, Suite 3300
Norfolk, VA 23529-0162
E-Mail:            jbrunelle@cs.odu.edu
Cell Phone:      757-536-1586
Fax:                757-826-8316

---

From: Justin Brunelle
Sent: Tuesday, April 21, 2015 11:34 AM
To: Thing342/MobileMemento; Thing342/MobileMemento
Subject: RE: [MobileMemento] FNF exception for some TimeMaps (#3)

The lanl aggr is not working properly. Sawood told us to use this one. Close enough for government work.

-- Justin F. Brunelle

-------- Original message --------
