### ISSUE TITLE
MobileMink immediately crashes when used on Android 4.4.4

### ISSUE THREAD

**Issue by machawk1** [Thing342/MobileMemento#4]
[Screencast](https://youtu.be/07NpSpL1XMA) of user experience on Android 4.4.4 with April 15, 2015 APK despite fix in #1.

@Thing342 @jbrunelle

**Comment by wjorda** [comment]
Are you compiling from source or using the APK? The server I have been using to host the APKs has been having issues, so I haven't been able to upload an updated APK yet. 

I also pushed an updated fix for #1 and #4 that fixes an unrelated bug that also breaks pre-21 compatability.

**Comment by machawk1** [comment]
I am using the provided APK and not compiling from source. I would be interested in re-testing the current source code when you can provide another APK. I do not have the setup to build Android apps at the moment, so must rely on binaries you provide.

**Comment by wjorda** [comment]
Here's a Google Drive link for the new APK: https://drive.google.com/file/d/0BzLqB7mw9TQTdzlOb3NuTVltU00/view?usp=sharing

I got this (mostly) working on my 4.4.2 emulator.

**Comment by machawk1** [comment]
This seems to work a little better.

For cnn.com I get the "Fetching Mementos..." popup and eventually a display. The message says that it might take a while but the BACK button on the device does not cancel this operation. I believe the press-back-to-cancel paradigm is familiar to most Android users.

The issue remains with URIs with a smaller number of mementos, for example, http://matkelly.com. I hit "Share" then "View Mementos" and the "Fetching Mementos..." popup as well as the Mobile Mink display for about a half second before the app crashes. 

I am using the APK you linked from Google Drive above.

**Comment by jbrunelle** [comment]
Wes and I had our meeting today. Looks like it's crashing when the mobile URIs don't have any mementos (you're spot on). He's working on a fix for that.

Justin F. Brunelle
Old Dominion University Department of Computer Science

## Web Science and Digital Libraries Research Group - PhD Student

Engineering & Computational Sciences Bldg
4700 Elkhorn Ave, Suite 3300
Norfolk, VA 23529-0162
E-Mail:            jbrunelle@cs.odu.edu
Cell Phone:      757-536-1586
Fax:                757-826-8316

**Comment by machawk1** [comment]
Verified the same behavior with Mobile Mink 0.5.1 on 201504301543 on 4.4.4 device.

Some dump info (from the emulator's debugger):

``` sh
04-30 18:33:35.006    1010-1289/org.mitre.mobilememento E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: org.mitre.mobilememento, PID: 1010
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NullPointerException
            at org.mitre.mobilememento.TimeMap.<init>(TimeMap.java:33)
            at org.mitre.mobilememento.TimeMap.union(TimeMap.java:54)
            at org.mitre.mobilememento.ViewArchiveActivity$GenerateTimeMapTask.doInBackground(ViewArchiveActivity.java:266)
            at org.mitre.mobilememento.ViewArchiveActivity$GenerateTimeMapTask.doInBackground(ViewArchiveActivity.java:224)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
```

and 

``` sh
04-30 18:33:37.666    1010-1010/org.mitre.mobilememento E/WindowManager﹕ android.view.WindowLeaked: Activity org.mitre.mobilememento.ViewArchiveActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{b1e54dc0 V.E..... R......D 0,0-1026,486} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:348)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:286)
            at android.app.ProgressDialog.show(ProgressDialog.java:116)
            at android.app.ProgressDialog.show(ProgressDialog.java:99)
            at android.app.ProgressDialog.show(ProgressDialog.java:94)
            at org.mitre.mobilememento.ViewArchiveActivity$GenerateTimeMapTask.onPreExecute(ViewArchiveActivity.java:234)
            at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
            at android.os.AsyncTask.execute(AsyncTask.java:535)
            at org.mitre.mobilememento.ViewArchiveActivity.onCreate(ViewArchiveActivity.java:70)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.access$800(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

from Android 4.4.2

**Comment by machawk1** [comment]
Digging into this bug. Familiar with Java but not Android dev, so pardon the verbosity. `this.contentUrl = others[0].contentUrl;` in the Timemap constructor is the source of the exception. others[0] is `null` for http://matkelly.com. Printing out the `others` array and the `contentUrl` if not null, I get:

``` Java
I/System.out( 7313): null
I/System.out( 7313): null
I/System.out( 7313): null
I/System.out( 7313): null
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ec018
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ec018 http://www2.matkelly.com/
I/System.out( 7313): null
I/System.out( 7313): null
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ec3d8
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ec3d8 http://www.m.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425cacd0
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425cacd0 http://www2.m.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c5798
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c5798 http://mobile.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c06a0
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c06a0 http://www.mobile.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ef228
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ef228 http://www2.mobile.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ee538
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ee538 http://wap.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c6010
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c6010 http://www.wap.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c6330
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c6330 http://www2.wap.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ee978
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425ee978 http://touch.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c5688
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c5688 http://www.touch.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@4258a220
I/System.out( 7313): org.mitre.mobilememento.TimeMap@4258a220 http://www2.touch.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c7c08
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425c7c08 http://mweb.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@4259e1b8
I/System.out( 7313): org.mitre.mobilememento.TimeMap@4259e1b8 http://www.mweb.matkelly.com/
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425e0da0
I/System.out( 7313): org.mitre.mobilememento.TimeMap@425e0da0 http://www2.mweb.matkelly.com/
```

The null TimeMaps are populated from ViewArchiveActivities' `maps[i] = threads.get(i).getTimeMap();`. Before looping through `others` at the end of the constructor, the `others[0].contentUrl;` must first be checked to determine if `others[0]` is null, as the getter for the contentUrl of null is the reason for the exception.

Pull request #9 fixes this and (verified) allows the app to work on Android 4.4.x.
